; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html



; 通过 ./scripts/cubemx_bsp_support_3_3_4.py 脚本生成CubeMX_Init并去入口化, 需要通过 cubemx_core_dir 指定 CubeMX 生成的 Core 目录
; 使用全局宏 TEST_MODE & TEST_EXAMPLE 控制编译时是否使用测试入口, 可用于测试单个具体模块


[platformio]
default_envs = black_f407zg

; ==================================================== 公共环境 ====================================================
[env]
platform = ststm32
framework = stm32cube
extra_scripts = pre:./scripts/cubemx_bsp_support_3_3_4.py
build_flags = 
	-Ilib
	-Itest
	; -DTEST_MODE -DTEST_EXAMPLE ; 快速闪烁 LED 测试

build_src_filter = 
	+<./**/*.c>
	+<../test/**/*.c>
	+<../lib/**/*.c>

; ==================================================== STM32F407ZG 环境 ====================================================
[env:black_f407zg]
extends = env
board = black_f407zg

cubemx_core_dir = ./boards/stm32f407zgt6/Core

build_flags = 
	${env.build_flags}
	-Iboards/stm32f407zgt6/CubeMX_Init
	-Iboards/stm32f407zgt6/BSP
	-Wl,--defsym=_Min_Heap_Size=0x200
	-Wl,--defsym=_Min_Stack_Size=0x400


build_src_filter = 
	${env.build_src_filter}
	+<../boards/stm32f407zgt6/CubeMX_Init/**/*.c>
	+<../boards/stm32f407zgt6/BSP/**/*.c>


upload_protocol = dfu
